# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 948bb645152b952c3d6d674d1620f6ba7766ebfb0b8a0e9e3c745c99dc646fd0ae69a669674abb3c6ebad7e9f9e792e24414f6178788819a5bc2c1a5a98f17bb

test:
  secret_key_base: 4b5578a57a0d3fa6fc8f04d856c809240f0fd6e700acd906cdc451938bf2558ae929f0ca228547df75bf73b173104a6991452e4e4d1c733b9b101346ab2b4723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
